import { View, Text, StyleSheet, Button, ActivityIndicator, Alert } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system';
import { useState } from 'react';

export default function ReportScreen() {
  const { uri, citations, solutions, location, auditorNotes } = useLocalSearchParams();
  const [generating, setGenerating] = useState(false);
  const router = useRouter();

  const generateAndSharePDF = async () => {
    setGenerating(true);
    try {
      // Create a local HTML template for the PDF
      // We need to convert the image URI to base64 if it's not a web URL,
      // but expo-print can sometimes handle local file URIs if formatted correctly.
      // For safety, let's read the image as base64.
      let imageBase64 = '';
      if (uri) {
        imageBase64 = await FileSystem.readAsStringAsync(uri as string, { encoding: 'base64' });
      }

      const html = `
        <html>
          <head>
            <style>
              body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
              h1 { color: #004085; border-bottom: 2px solid #004085; padding-bottom: 10px; }
              .section { margin-top: 20px; }
              .label { font-weight: bold; font-size: 14px; color: #555; text-transform: uppercase; margin-bottom: 5px; }
              .content { font-size: 16px; margin-bottom: 15px; padding: 10px; background-color: #f8f9fa; border-left: 4px solid #004085; white-space: pre-wrap; }
              .image-container { text-align: center; margin-top: 20px; }
              img { max-width: 100%; max-height: 400px; border-radius: 8px; border: 1px solid #ddd; }
              .footer { margin-top: 40px; font-size: 12px; color: #777; text-align: center; border-top: 1px solid #ddd; padding-top: 10px; }
            </style>
          </head>
          <body>
            <h1>SafeScope Audit Report</h1>
            
            <div class="section">
              <div class="label">Date & Time</div>
              <div class="content">${new Date().toLocaleString()}</div>
            </div>

            <div class="section">
              <div class="label">Location / Area</div>
              <div class="content">${location || 'Not specified'}</div>
            </div>

            <div class="section">
              <div class="label">MSHA/OSHA Citations</div>
              <div class="content">${citations || 'None identified'}</div>
            </div>

            <div class="section">
              <div class="label">Recommended Solutions</div>
              <div class="content">${solutions || 'None provided'}</div>
            </div>

            <div class="section">
              <div class="label">Auditor Notes</div>
              <div class="content">${auditorNotes || 'No additional notes'}</div>
            </div>

            ${imageBase64 ? `
            <div class="image-container">
              <div class="label" style="text-align: left;">Hazard Photo</div>
              <img src="data:image/jpeg;base64,${imageBase64}" />
            </div>
            ` : ''}

            <div class="footer">
              Generated by SafeScope using Google Gemini AI
            </div>
          </body>
        </html>
      `;

      const { uri: pdfUri } = await Print.printToFileAsync({ html });
      
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(pdfUri, {
          mimeType: 'application/pdf',
          dialogTitle: 'Share Audit Report',
          UTI: 'com.adobe.pdf'
        });
        
        // Return to home after sharing
        router.dismissAll();
      } else {
        Alert.alert('Sharing Unavailable', 'PDF generated at: ' + pdfUri);
      }

    } catch (error: any) {
      Alert.alert('Error', error.message || 'Failed to generate PDF.');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <View style={styles.container}>
      <Text style={styles.title}>Report Ready</Text>
      <Text style={styles.subtitle}>Your audit details are ready to be converted into a formal PDF report.</Text>
      
      {generating ? (
        <ActivityIndicator size="large" color="#007AFF" />
      ) : (
        <View>
          <Button title="Generate & Share PDF" onPress={generateAndSharePDF} />
          <View style={{height: 20}} />
          <Button title="Back to Edit" color="#888" onPress={() => router.back()} />
        </View>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#333',
  },
  subtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 40,
  },
});
