import { Injectable } from '@nestjs/common';

@Injectable()
export class PdfService {
  generateExecutivePdf(data: any): Buffer {
    const escapePdf = (value: any) =>
      String(value ?? '')
        .replace(/\\/g, '\\\\')
        .replace(/\(/g, '\\(')
        .replace(/\)/g, '\\)')
        .replace(/\r?\n/g, '\\n');

    const lines = [
      'Sentinel Safety Executive Report',
      '',
      `Report ID: ${data.reportId}`,
      `Generated: ${new Date(data.generatedAt).toLocaleString()}`,
      '',
      `Total Findings: ${data.totalFindings}`,
      `High-Risk Findings: ${data.highRiskFindings}`,
      `Dominant Hazard: ${String(data.dominantHazard || 'Unknown').replace(/_/g, ' ')}`,
      '',
      'Executive Summary',
      '',
      data.summary || 'No executive summary available.',
      '',
      'Generated by Sentinel Safety / SafeScope.',
      'Suggested standards support review. Final compliance determinations remain with qualified safety personnel.',
    ];

    const text = lines
      .flatMap((line) => String(line).split('\n'))
      .map((line, index) => `BT /F1 11 Tf 50 ${760 - index * 16} Td (${escapePdf(line)}) Tj ET`)
      .join('\n');

    const objects = [
      '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
      '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
      '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
      '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
      `5 0 obj << /Length ${Buffer.byteLength(text)} >> stream\n${text}\nendstream endobj`,
    ];

    let pdf = '%PDF-1.4\n';
    const offsets = [0];

    for (const obj of objects) {
      offsets.push(Buffer.byteLength(pdf));
      pdf += obj + '\n';
    }

    const xrefOffset = Buffer.byteLength(pdf);
    pdf += `xref\n0 ${objects.length + 1}\n`;
    pdf += '0000000000 65535 f \n';
    for (let i = 1; i <= objects.length; i++) {
      pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
    }

    pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

    return Buffer.from(pdf);
  }
}
