import { Injectable } from '@nestjs/common';
const PDFDocument = require('pdfkit');

@Injectable()
export class PdfService {
  async generateExecutivePdf(data: any): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 50 });
    const buffers: any[] = [];
    doc.on('data', buffers.push.bind(buffers));

    const {
      overview,
      riskEvaluation,
      standards,
      correctiveActions,
      complianceNote,
      metadata,
    } = data;

    // ===== Header =====
    const path = require("path");
    const logoPath = path.join(process.cwd(), "src/assets/logo.png");
    try { doc.image(logoPath, 50, 45, { width: 50 }); } catch (e) { console.warn("Logo missing"); }
    doc.moveDown(1);
    doc
      .fontSize(20)
      .fillColor('#1f4e79')
      .text('Sentinel Safety', { align: 'left' });

    doc
      .fontSize(10)
      .fillColor('#666666')
      .text('See Risk. Prevent Harm.', { align: 'left' });

    doc.moveDown(1.2);

    doc
      .fontSize(16)
      .fillColor('#000000')
      .text('Executive Summary', { underline: true });

    doc.moveDown(1);

    // ===== Helper for sections =====
    const section = (title: string, body: string) => {
      doc
        .fontSize(12)
        .fillColor('#1f4e79')
        .text(title, { continued: false });

      doc
        .moveDown(0.3)
        .fontSize(11)
        .fillColor('#000000')
        .text(body, { align: 'left' });

      doc.moveDown(0.8);
    };

    // ===== Sections =====
    section('Overview', overview);
    section('Risk Evaluation', riskEvaluation);
    section('Applicable Standards', standards);
    section('Corrective Actions', correctiveActions);
    section('Compliance Note', complianceNote);

    // ===== Divider =====
    doc.moveDown(0.5);
    doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown(0.8);

    // ===== Metadata =====
    doc
      .fontSize(10)
      .fillColor('#333333')
      .text(`Severity: ${metadata.severity}`);
    doc.text(`Findings Count: ${metadata.findingsCount}`);

    // ===== Footer =====
    doc.moveDown(2);
    doc
      .fontSize(8)
      .fillColor('#888888')
      .text('Generated by Sentinel Safety • SafeScope Engine', { align: 'center' });

    doc.end();

    return await new Promise((resolve) => {
      doc.on('end', () => resolve(Buffer.concat(buffers)));
    });
  }
}
