import React from 'react';

export const FinalReportTemplate = ({ session }: { session: any }) => (
  <div className="p-10 font-serif max-w-4xl mx-auto border" id="printable-report">
    <style>{ `
      @media print {
        .page-break { page-break-before: always; }
        body { -webkit-print-color-adjust: exact; }
      }
    ` }</style>
    
    <div className="text-center mb-10">
      <h1 className="text-4xl font-bold mb-4">Sentinel Safety Audit Report</h1>
      <p className="text-lg">Facility: {session.siteId}</p>
      <p className="text-lg">Date: {new Date(session.createdAt).toLocaleDateString()}</p>
      <div className="mt-5 p-4 border italic">Confidential – Internal Use Only</div>
    </div>

    <section className="mb-10">
      <h2 className="text-2xl font-bold mb-4 border-b">Executive Summary</h2>
      <p>{session.sessionNotes || 'No summary provided.'}</p>
    </section>

    <div className="page-break" />

    <section>
      <h2 className="text-2xl font-bold mb-4 border-b">Detailed Findings</h2>
      {session.entries.map((entry: any, i: number) => (
        <div key={entry.id} className="mb-8 p-4 border rounded">
          <h3 className="font-bold text-lg mb-2">Finding {i + 1}: {entry.locationText}</h3>
          <p className="mb-4">{entry.notes}</p>
          {entry.findings.map((f: any) => (
            <div key={f.id} className="mt-2 text-sm bg-gray-100 p-4 rounded">
              <p><strong>Hazard:</strong> {f.identifiedHazards.join(', ')}</p>
              <p><strong>Severity:</strong> {f.severity}</p>
              <p><strong>Standard:</strong> {f.applicableStandards.join(', ')}</p>
              <p><strong>Fix:</strong> {f.suggestedFix}</p>
            </div>
          ))}
        </div>
      ))}
    </section>

    <footer className="mt-20 text-center text-xs text-gray-500 border-t pt-5">
      <p>© Christopher McKinley. All rights reserved.</p>
      <p>Generated by Sentinel Safety | Internal Use Only</p>
    </footer>
  </div>
);
