import { Standard } from '../entities/standard.entity';

export const standardSeeds: Array<Partial<Standard>> = [
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14107',
    citation: '30 CFR 56.14107',
    heading: 'Moving machine parts',
    standardText: 'Guards shall be provided and maintained to protect persons from moving machine parts.',
    summaryPlainLanguage: 'Moving machine parts must be guarded where contact could injure a person.',
    keywords: ['guard', 'guarding', 'moving parts', 'machine', 'belt', 'pulley', 'conveyor', 'rotating'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.11001',
    citation: '30 CFR 56.11001',
    heading: 'Safe access',
    standardText: 'Safe means of access shall be provided and maintained to all working places.',
    summaryPlainLanguage: 'Workers must have safe access to working areas.',
    keywords: ['access', 'walkway', 'ladder', 'platform', 'stairs', 'travelway', 'working place'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.20003',
    citation: '30 CFR 56.20003',
    heading: 'Housekeeping',
    standardText: 'Workplaces, passageways, storerooms, and service rooms shall be kept clean and orderly.',
    summaryPlainLanguage: 'Work areas and travelways must be kept clean and orderly.',
    keywords: ['housekeeping', 'trash', 'debris', 'slip', 'trip', 'walkway', 'material'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.12004',
    citation: '30 CFR 56.12004',
    heading: 'Electrical conductors',
    standardText: 'Electrical conductors exposed to mechanical damage shall be protected.',
    summaryPlainLanguage: 'Electrical wires and conductors must be protected from damage.',
    keywords: ['electrical', 'wire', 'conductor', 'cord', 'damage', 'exposed', 'panel'],
  },
  {
    source: 'OSHA',
    titleNumber: '29',
    part: '1910',
    section: '1910.22',
    citation: '29 CFR 1910.22',
    heading: 'Walking-working surfaces',
    standardText: 'Walking-working surfaces shall be inspected, regularly and as necessary, and maintained in a safe condition.',
    summaryPlainLanguage: 'Walking and working surfaces must be kept safe and maintained.',
    keywords: ['walking surface', 'working surface', 'slip', 'trip', 'fall', 'floor', 'walkway'],
  },
];
