import { Standard } from '../entities/standard.entity';

export const standardSeeds: Array<Partial<Standard>> = [
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14107',
    citation: '30 CFR 56.14107',
    heading: 'Moving machine parts',
    standardText: 'Guards shall be provided and maintained to protect persons from moving machine parts.',
    summaryPlainLanguage: 'Moving machine parts must be guarded where contact could injure a person.',
    keywords: ['guard', 'gard', 'guarded', 'protection', 'moving parts', 'belt', 'roller', 'pinch point', 'pulley', 'conveyor', 'rotating', 'crusher', 'shaft', 'coupling', 'head pulley', 'tail pulley', 'gearbox', 'rotating shaft'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.11001',
    citation: '30 CFR 56.11001',
    heading: 'Safe access',
    standardText: 'Safe means of access shall be provided and maintained to all working places.',
    summaryPlainLanguage: 'Workers must have safe access to working areas.',
    keywords: ['access', 'safe access', 'ingress', 'egress', 'climb', 'walkway', 'travelway', 'ladder', 'latter', 'platform', 'deck', 'catwalk', 'stair', 'stairs', 'steps', 'step', 'handrail', 'rail', 'grating', 'working place', 'screen tower', 'crusher deck', 'work area'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.20003',
    citation: '30 CFR 56.20003',
    heading: 'Housekeeping',
    standardText: 'Workplaces, passageways, storerooms, and service rooms shall be kept clean and orderly.',
    summaryPlainLanguage: 'Work areas and travelways must be kept clean and orderly.',
    keywords: ['housekeeping', 'cleanup', 'clean', 'orderly', 'trash', 'debris', 'scrap', 'clutter', 'spill', 'oil', 'mud', 'slip', 'trip', 'walkway', 'passageway', 'material', 'stored material', 'loose aggregate'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.12004',
    citation: '30 CFR 56.12004',
    heading: 'Electrical conductors',
    standardText: 'Electrical conductors exposed to mechanical damage shall be protected.',
    summaryPlainLanguage: 'Electrical wires and conductors must be protected from damage.',
    keywords: ['electrical', 'electric', 'power', 'energized', 'live', 'voltage', 'wire', 'wiring', 'conductor', 'cord', 'cable', 'extension cord', 'insulation', 'short', 'damage', 'damaged', 'exposed', 'panel', 'junction box', 'disconnect', 'breaker'],
  },
  {
    source: 'OSHA',
    titleNumber: '29',
    part: '1910',
    section: '1910.22',
    citation: '29 CFR 1910.22',
    heading: 'Walking-working surfaces',
    standardText: 'Walking-working surfaces shall be inspected, regularly and as necessary, and maintained in a safe condition.',
    summaryPlainLanguage: 'Walking and working surfaces must be kept safe and maintained.',
    keywords: ['walking surface', 'working surface', 'slip', 'trip', 'fall', 'floor', 'walkway', 'platform', 'edge', 'elevated', 'guardrail', 'open edge'],
  },,

  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.9300',
    citation: '30 CFR 56.9300',
    heading: 'Berms and guardrails',
    standardText: 'Berms or guardrails shall be provided and maintained on the banks of roadways where a drop-off exists.',
    summaryPlainLanguage: 'Elevated roadways and travel areas must have berms or guardrails where drop-offs create risk.',
    keywords: ['berm', 'berms', 'berm missing', 'guardrail', 'haul road', 'roadway', 'drop off', 'drop-off', 'elevated road', 'dump point', 'edge protection', 'road edge', 'travelway edge', 'truck road'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14131',
    citation: '30 CFR 56.14131',
    heading: 'Seat belts',
    standardText: 'Seat belts shall be provided and worn in haulage trucks and other mobile equipment where there is a danger of overturning.',
    summaryPlainLanguage: 'Seat belts must be provided and used where mobile equipment rollover or overturn hazards exist.',
    keywords: ['seat belt', 'seatbelt', 'seat belts', 'no seatbelt', 'loader', 'front end loader', 'haul truck', 'dump truck', 'dozer', 'excavator', 'skid steer', 'forklift', 'mobile equipment', 'operator restraint', 'not wearing seat belt'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14132',
    citation: '30 CFR 56.14132',
    heading: 'Horns and backup alarms',
    standardText: 'Manually operated horns or other audible warning devices shall be provided on self-propelled mobile equipment.',
    summaryPlainLanguage: 'Mobile equipment must have effective audible warning devices such as horns or backup alarms.',
    keywords: ['backup alarm', 'back up alarm', 'back-up alarm', 'backup beeper', 'beeper', 'horn', 'warning device', 'audible alarm', 'reverse alarm', 'haul truck alarm', 'loader alarm', 'mobile equipment alarm'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.15020',
    citation: '30 CFR 56.15020',
    heading: 'Eye protection',
    standardText: 'All persons shall wear safety glasses, goggles, or face shields or other suitable protective devices when in or around an area of a mine or plant where a hazard exists which could cause injury to unprotected eyes.',
    summaryPlainLanguage: 'Eye and face protection must be used where eye injury hazards exist.',
    keywords: ['eye protection', 'ppe', 'hard hat', 'helmet', 'safety glasses', 'glasses', 'goggles', 'face shield', 'faceshield', 'visor', 'grinding', 'cutting', 'flying particles', 'metal chips', 'no glasses', 'no face shield'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.15004',
    citation: '30 CFR 56.15004',
    heading: 'Safety belts and lines',
    standardText: 'Safety belts and lines shall be worn when persons work where there is danger of falling.',
    summaryPlainLanguage: 'Fall protection must be used where persons are exposed to fall hazards.',
    keywords: ['fall protection', 'fall hazard', 'working at height', 'elevated platform', 'open edge', 'unprotected edge', 'harness', 'lanyard', 'safety line', 'tie off', 'tie-off', 'edge without protection'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.15003',
    citation: '30 CFR 56.15003',
    heading: 'Protective footwear',
    standardText: 'All persons shall wear suitable protective footwear when in or around an area of a mine or plant where a hazard exists which could cause injury to the feet.',
    summaryPlainLanguage: 'Protective footwear must be worn where foot injury hazards exist.',
    keywords: ['boots', 'safety boots', 'protective footwear', 'steel toe', 'foot protection', 'foot hazard', 'crushing foot hazard'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.15001',
    citation: '30 CFR 56.15001',
    heading: 'First-aid materials',
    standardText: 'Adequate first-aid materials, including stretchers and blankets, shall be provided at places convenient to all working areas.',
    summaryPlainLanguage: 'First-aid supplies must be available and convenient to working areas.',
    keywords: ['first aid', 'first-aid', 'first aid kit', 'stretcher', 'blanket', 'medical supplies'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.16006',
    citation: '30 CFR 56.16006',
    heading: 'Protection of persons near moving equipment',
    standardText: 'Persons shall not position themselves where they will be exposed to hazards from moving equipment.',
    summaryPlainLanguage: 'People must be protected from being struck or exposed to hazards from moving equipment.',
    keywords: ['pedestrian', 'person near equipment', 'mobile equipment', 'traffic control', 'blind spot', 'struck by', 'near loader', 'near haul truck', 'equipment interaction', 'spotter'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.4600',
    citation: '30 CFR 56.4600',
    heading: 'Extinguishing equipment',
    standardText: 'Firefighting equipment shall be provided, maintained, and readily accessible.',
    summaryPlainLanguage: 'Fire extinguishers and firefighting equipment must be maintained and accessible.',
    keywords: ['fire extinguisher', 'extinguisher', 'fire ext', 'extingusher', 'blocked extinguisher', 'fire protection', 'fire equipment', 'fire suppression', 'suppression system', 'hot work', 'welding', 'torch', 'spark', 'flammable', 'fuel', 'combustible', 'blocked access'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14211',
    citation: '30 CFR 56.14211',
    heading: 'Blocking equipment in raised position',
    standardText: 'Persons shall not work on or from a piece of mobile equipment in a raised position until it has been securely blocked in position.',
    summaryPlainLanguage: 'Raised equipment must be securely blocked before work is performed.',
    keywords: ['blocked equipment', 'raised equipment', 'maintenance', 'repair', 'blocking', 'jack', 'lifted equipment', 'unsupported equipment'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.14132',
    citation: '30 CFR 56.14132',
    heading: 'Horns and backup alarms',
    standardText: 'Mobile equipment shall be equipped with an audible warning device.',
    summaryPlainLanguage: 'Mobile equipment must have working backup alarms and horns.',
    keywords: ['alarm', 'horn', 'backup', 'back-up', 'mobile equipment', 'loader', 'truck', 'haul truck', 'beeper', 'warning'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.15006',
    citation: '30 CFR 56.15006',
    heading: 'Protective equipment',
    standardText: 'Protective equipment and clothing shall be worn as necessary.',
    summaryPlainLanguage: 'Personal Protective Equipment (PPE) is required when exposed to hazards.',
    keywords: ['ppe', 'glove', 'gloves', 'eye protection', 'glasses', 'face shield', 'faceshield', 'hard hat', 'boots', 'safety boots', 'foot protection', 'safety gear'],
  },
  {
    source: 'MSHA',
    titleNumber: '30',
    part: '56',
    section: '56.9300',
    citation: '30 CFR 56.9300',
    heading: 'Berms and guardrails',
    standardText: 'Berms or guardrails shall be provided and maintained on the banks of roadways where a drop-off exists.',
    summaryPlainLanguage: 'Elevated roadways and travel areas must have berms or guardrails.',
    keywords: ['berm', 'berms', 'haul road', 'roadway', 'drop-off', 'drop off', 'road edge', 'traffic control', 'haulage road'],
  },
];
