import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface InspectionData {
  adminInfo: any;
  findings: any[];
}

interface ExportOptions {
  findingsPerPage: 'single' | 'multiple';
}

// 🔷 HELPER: CONVERT BLOB URL TO BASE64 (Required for jsPDF)
const blobToBase64 = async (blobUrl: string): Promise<string> => {
  if (!blobUrl || blobUrl.startsWith('mock')) return ''; // Skip mock data in lab
  try {
    const response = await fetch(blobUrl);
    const blob = await response.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch (e) {
    console.error('Photo conversion error:', e);
    return '';
  }
};

export const localExporter = {
  // 🔷 EXPORT RAW DATA (ENCRYPTED JSON)
  exportDataFile: (data: InspectionData) => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `sentinel-inspection-${data.adminInfo?.site || 'export'}-${new Date().toISOString().split('T')[0]}.json`;
    link.click();
    URL.revokeObjectURL(url);
  },

  // 🔷 GENERATE C-SUITE PDF LOCALLY
  generatePDF: async (data: InspectionData, options: ExportOptions = { findingsPerPage: 'single' }) => {
    const doc = await localExporter._buildDoc(data, options);
    doc.save(`SENTINEL-REPORT-${data.adminInfo?.site || 'EXPORT'}-${new Date().getTime()}.pdf`);
  },

  // 🔷 PREVIEW PDF IN NEW TAB
  previewPDF: async (data: InspectionData, options: ExportOptions = { findingsPerPage: 'single' }) => {
    const doc = await localExporter._buildDoc(data, options);
    const blobUrl = doc.output('bloburl');
    window.open(blobUrl);
  },

  // 🔷 INTERNAL DOC BUILDER
  _buildDoc: async (data: InspectionData, options: ExportOptions) => {
    const doc = new jsPDF();
    const { adminInfo, findings } = data;
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const centerX = pageWidth / 2;

    const addHeaderFooter = (d: any) => {
      const pageCount = d.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        d.setPage(i);
        d.setFontSize(8);
        d.setTextColor(148, 163, 184); 
        d.text('SENTINEL SAFETY INTELLIGENCE REPORT', 20, 10);
        d.text(`SITE: ${adminInfo?.site || 'N/A'}`, pageWidth - 20, 10, { align: 'right' });
        d.setDrawColor(226, 232, 240);
        d.line(20, 12, pageWidth - 20, 12);
        d.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
        d.text('GENERATED BY SENTINEL PRO (MILITARY-GRADE PRECISION)', 20, pageHeight - 10);
      }
    };

    // 1. COVER PAGE
    doc.setTextColor(15, 23, 42); // Navy
    doc.setFontSize(32);
    doc.setFont('helvetica', 'bold');
    doc.text('SAFETY INSPECTION', centerX, 120, { align: 'center' });
    doc.text('EXECUTIVE REPORT', centerX, 132, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('SYSTEM-GENERATED COMPLIANCE AUDIT', centerX, 145, { align: 'center' });
    doc.setDrawColor(249, 115, 22);
    doc.line(60, 155, pageWidth - 60, 155);
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text(adminInfo?.company || 'Organization Name', centerX, 165, { align: 'center' });
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    doc.text(adminInfo?.site || 'N/A', centerX, 177, { align: 'center' });
    doc.setFontSize(12);
    doc.setTextColor(100, 116, 139);
    doc.text(adminInfo?.inspector || 'N/A', centerX, 187, { align: 'center' });
    doc.text(adminInfo?.date || 'N/A', centerX, 195, { align: 'center' });

    if (adminInfo?.isConfidential) {
      doc.setTextColor(185, 28, 28);
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('PRIVILEGED & CONFIDENTIAL - INTERNAL USE ONLY', pageWidth / 2, pageHeight - 30, { align: 'center' });
    }

    // 2. EXECUTIVE SUMMARY PAGE
    doc.addPage();
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('EXECUTIVE SUMMARY', 20, 35);
    
    const highRisk = findings.filter(f => (f.likelihood * f.severity) >= 15).length;
    const medRisk = findings.filter(f => (f.likelihood * f.severity) >= 5 && (f.likelihood * f.severity) < 15).length;
    const lowRisk = findings.filter(f => (f.likelihood * f.severity) < 5).length;
    const avgRisk = findings.length > 0 
      ? (findings.reduce((acc, f) => acc + (f.likelihood * f.severity), 0) / findings.length).toFixed(1)
      : 0;

    autoTable(doc, {
      startY: 45,
      head: [['Metric', 'Value', 'Assessment']],
      body: [
        ['Total Findings Logged', findings.length, 'Comprehensive'],
        ['Critical Risks (RPN 15+)', highRisk, highRisk > 0 ? 'URGENT ACTION' : 'STABLE'],
        ['Moderate Risks (RPN 5-14)', medRisk, 'MONITORING'],
        ['Low Risks (RPN 1-4)', lowRisk, 'CONTROLLED'],
        ['Avg. Risk Priority Number', avgRisk, parseFloat(avgRisk as string) > 12 ? 'CRITICAL' : 'OPTIMAL'],
      ],
      headStyles: { fillColor: [15, 23, 42] },
      theme: 'striped'
    });

    const chartY = (doc as any).lastAutoTable.finalY + 20;
    doc.setFontSize(12);
    doc.text('RISK DISTRIBUTION ANALYSIS', 20, chartY);
    const maxVal = Math.max(highRisk, medRisk, lowRisk, 1);
    const barWidth = 100;
    doc.setFillColor(34, 197, 94);
    doc.rect(20, chartY + 10, (lowRisk / maxVal) * barWidth, 8, 'F');
    doc.setTextColor(100);
    doc.setFontSize(8);
    doc.text(`LOW: ${lowRisk}`, 25 + (lowRisk / maxVal) * barWidth, chartY + 16);
    doc.setFillColor(234, 179, 8);
    doc.rect(20, chartY + 22, (medRisk / maxVal) * barWidth, 8, 'F');
    doc.text(`MED: ${medRisk}`, 25 + (medRisk / maxVal) * barWidth, chartY + 28);
    doc.setFillColor(239, 68, 68);
    doc.rect(20, chartY + 34, (highRisk / maxVal) * barWidth, 8, 'F');
    doc.text(`HIGH: ${highRisk}`, 25 + (highRisk / maxVal) * barWidth, chartY + 40);

    // 🔷 3. NEW: QUICK REFERENCE LIST (TABLE OF CONTENTS)
    doc.addPage();
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('QUICK REFERENCE LIST', 20, 35);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    doc.text('A concise summary of all identified hazards and their locations.', 20, 42);

    autoTable(doc, {
      startY: 50,
      head: [['ID', 'Hazard Category', 'Explanation']],
      body: findings.map((f, i) => [
        i + 1,
        f.category,
        f.description
      ]),
      headStyles: { fillColor: [15, 23, 42] },
      columnStyles: {
        0: { cellWidth: 15 },
        1: { cellWidth: 50, fontStyle: 'bold' },
        2: { cellWidth: 'auto' }
      },
      theme: 'grid'
    });

    // 4. DETAILED FINDINGS
    let currentY = 30;
    
    for (let i = 0; i < findings.length; i++) {
      const f = findings[i];
      const rpn = f.likelihood * f.severity;
      let rpnColor: [number, number, number] = [34, 197, 94]; 
      if (rpn >= 5) rpnColor = [234, 179, 8]; 
      if (rpn >= 15) rpnColor = [249, 115, 22]; 
      if (rpn >= 21) rpnColor = [239, 68, 68]; 

      if (options.findingsPerPage === 'single' || i === 0) {
        doc.addPage();
        currentY = 30;
      } else if (currentY > pageHeight - 100) {
        doc.addPage();
        currentY = 30;
      }

      // Title & Badge Row
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`FINDING #${i + 1}: ${f.category}`, 20, currentY);
      
      doc.setFillColor(rpnColor[0], rpnColor[1], rpnColor[2]);
      doc.roundedRect(pageWidth - 50, currentY - 8, 30, 10, 1, 1, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.text(`RPN: ${rpn}`, pageWidth - 35, currentY - 1, { align: 'center' });
      
      currentY += 12;

      // Description
      const descLines = doc.splitTextToSize(f.description, pageWidth - 40);
      doc.setTextColor(71, 85, 105);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.text('DESCRIPTION', 20, currentY);
      doc.setFont('helvetica', 'normal');
      doc.text(descLines, 20, currentY + 6);
      currentY += (descLines.length * 5) + 12;

      // Standard
      doc.setFont('helvetica', 'bold');
      doc.text('REGULATORY STANDARD', 20, currentY);
      doc.setTextColor(3, 105, 161);
      doc.setFont('helvetica', 'normal');
      doc.text('MSHA 56.11002 - Handrails and toeboards', 20, currentY + 6);
      currentY += 15;

      // Action
      const actionLines = doc.splitTextToSize(f.action || 'No action specified.', pageWidth - 40);
      doc.setTextColor(71, 85, 105);
      doc.setFont('helvetica', 'bold');
      doc.text('CORRECTIVE ACTION', 20, currentY);
      doc.setFont('helvetica', 'normal');
      doc.text(actionLines, 20, currentY + 6);
      currentY += (actionLines.length * 5) + 15;

      // 🔷 5. NEW: PHOTO EVIDENCE INCLUSION
      if (f.photos && f.photos.length > 0) {
        doc.setFont('helvetica', 'bold');
        doc.text('EVIDENCE PHOTOS', 20, currentY);
        currentY += 6;
        
        let photoX = 20;
        for (const photoUrl of f.photos.slice(0, 2)) {
          const base64 = await blobToBase64(photoUrl);
          if (base64) {
            try {
              doc.addImage(base64, 'JPEG', photoX, currentY, 80, 60);
            } catch (e) {
              doc.setDrawColor(226, 232, 240);
              doc.rect(photoX, currentY, 80, 60);
              doc.text('IMAGE LOAD ERROR', photoX + 40, currentY + 30, { align: 'center' });
            }
          } else {
            doc.setDrawColor(226, 232, 240);
            doc.rect(photoX, currentY, 80, 60);
            doc.setFontSize(7);
            doc.text('PHOTO EVIDENCE (MOCK)', photoX + 40, currentY + 30, { align: 'center' });
          }
          photoX += 85;
        }
        currentY += 70;
      }

      // Separator Line (only for multiple)
      if (options.findingsPerPage === 'multiple' && i < findings.length - 1) {
        doc.setDrawColor(241, 245, 249);
        doc.line(20, currentY - 5, pageWidth - 20, currentY - 5);
        currentY += 10;
      }
    }

    addHeaderFooter(doc);
    return doc;
  }
};
